document.addEventListener('DOMContentLoaded',function(){initMobileMenu();initSmoothScroll();initScrollEffects();initPartnersSlider();initMenuHighlight()});function initMobileMenu(){const menuToggle=document.querySelector('.menu-toggle');const menu=document.querySelector('.menu');if(menuToggle){menuToggle.addEventListener('click',function(){menu.classList.toggle('active');this.innerHTML=menu.classList.contains('active')?'<i class="fas fa-times"></i>':'<i class="fas fa-bars"></i>'})}
const menuLinks=document.querySelectorAll('.menu a');menuLinks.forEach(link=>{link.addEventListener('click',function(){if(menu.classList.contains('active')){menu.classList.remove('active');if(menuToggle){menuToggle.innerHTML='<i class="fas fa-bars"></i>'}}})})}
function initSmoothScroll(){const links=document.querySelectorAll('a[href^="#"]');links.forEach(link=>{link.addEventListener('click',function(e){e.preventDefault();const targetId=this.getAttribute('href').substring(1);const targetElement=document.getElementById(targetId);if(targetElement){const offsetTop=targetElement.offsetTop-80;window.scrollTo({top:offsetTop,behavior:'smooth'})}})})}
function initScrollEffects(){const header=document.querySelector('header');function checkScroll(){if(window.scrollY>100){header.classList.add('scrolled')}else{header.classList.remove('scrolled')}}
checkScroll();window.addEventListener('scroll',checkScroll)}
function initPartnersSlider(){const slider=document.querySelector('.parceiros-slider');if(slider){const items=slider.querySelectorAll('.parceiro-item');let currentIndex=0;let visibleItems=getVisibleItems();function getVisibleItems(){if(window.innerWidth<768){return 1}else if(window.innerWidth<992){return 2}else{return 4}}
function updateSlider(){items.forEach((item,index)=>{if(index>=currentIndex&&index<currentIndex+visibleItems){item.style.display='block'}else{item.style.display='none'}})}
function nextSlide(){currentIndex++;if(currentIndex>items.length-visibleItems){currentIndex=0}
updateSlider()}
updateSlider();setInterval(nextSlide,3000);window.addEventListener('resize',function(){visibleItems=getVisibleItems();updateSlider()})}}
function initMenuHighlight(){const menuLinks=document.querySelectorAll('.menu-destacado');menuLinks.forEach(link=>{link.style.fontWeight='600';link.style.fontSize='1.1rem';link.style.padding='10px 20px';link.style.boxShadow='0 2px 4px rgba(0,0,0,0.1)';link.addEventListener('mouseenter',function(){if(!this.classList.contains('active')){this.style.transform='translateY(-3px)';this.style.boxShadow='0 4px 8px rgba(0,0,0,0.15)'}});link.addEventListener('mouseleave',function(){if(!this.classList.contains('active')){this.style.transform='translateY(0)';this.style.boxShadow='0 2px 4px rgba(0,0,0,0.1)'}})})}
